services:
  iot-db:
    image: postgres:14
    container_name: iot-db
    restart: always
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot_user -d iot_db || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  api:
    build: .
    container_name: iot-api
    depends_on:
      - iot-db
    command: ["./wait-for-it.sh", "iot-db:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: iot-db
      DB_NAME: iot_db
      DB_USER: iot_user
      DB_PASSWORD: iot_pass


volumes:
  pgdata:
